"use strict";
try{
    let z = 10;
    miFuncion();
}
catch(error){
    console.log(error);
}
finally{
    console.log("Finalmente");
}
console.log("continuamos.....");